apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: nodespeed-forb-luas-ml
  namespace: default
spec:
  secretName: nodespeed-forb-luas-ml-tls
  issuerRef:
    name: letsencrypt
  commonName: nodespeed.forb.luas.ml
  dnsNames:
  - nodespeed.forb.luas.ml
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - nodespeed.forb.luas.ml